// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportFile() {
  return window['go']['pkg']['App']['ImportFile']();
}
